// <auto-generated />
using System;
using DevSpaceWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DevSpaceWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230527060451_Init2")]
    partial class Init2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DevSpaceWeb.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsOur")
                        .HasColumnType("bit");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatId = 1,
                            IsOur = true,
                            MessageDate = new DateTime(2023, 5, 27, 12, 4, 51, 893, DateTimeKind.Local).AddTicks(7297),
                            MessageText = "Hi",
                            UserId = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 2,
                            ChatId = 1,
                            IsOur = false,
                            MessageDate = new DateTime(2023, 5, 27, 12, 5, 51, 893, DateTimeKind.Local).AddTicks(7312),
                            MessageText = "Hello",
                            UserId = 2,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 3,
                            ChatId = 1,
                            IsOur = true,
                            MessageDate = new DateTime(2023, 5, 27, 12, 6, 51, 893, DateTimeKind.Local).AddTicks(7317),
                            MessageText = "How are you?",
                            UserId = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 4,
                            ChatId = 1,
                            IsOur = false,
                            MessageDate = new DateTime(2023, 5, 27, 12, 7, 51, 893, DateTimeKind.Local).AddTicks(7318),
                            MessageText = "I'm good, thanks!",
                            UserId = 2,
                            UserName = "Alice"
                        },
                        new
                        {
                            Id = 5,
                            ChatId = 1,
                            IsOur = true,
                            MessageDate = new DateTime(2023, 5, 27, 12, 8, 51, 893, DateTimeKind.Local).AddTicks(7321),
                            MessageText = "What have you been up to?",
                            UserId = 1,
                            UserName = "Bob"
                        },
                        new
                        {
                            Id = 6,
                            ChatId = 1,
                            IsOur = false,
                            MessageDate = new DateTime(2023, 5, 27, 12, 9, 51, 893, DateTimeKind.Local).AddTicks(7323),
                            MessageText = "Not much, just working on a project",
                            UserId = 2,
                            UserName = "Alice"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
